Algoritmo "consumo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Nélio Alves 
// Data atual  : 14/09/2025
Var

   distancia, combustivel, media: real


Inicio

      escreval("Distancia percorrida: ")
      leia(distancia)
      escreval("Combustível gasto: ")
      leia(combustivel)
      
      media <- distancia / combustivel
      
      escreva("Consumo medio = ", media:8:3)
      
Fimalgoritmo